version: "3.9"

services:
  api:
    build: ./neoview-backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/neoview_db
      - FUSEKI_URL=http://fuseki:3030/knowledge
    depends_on:
      - mongo
      - fuseki
    networks:
      - knowledge_net

  mongo:
    image: mongo:6.0
    platform: linux/amd64
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=neoview_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - knowledge_net

  fuseki:
    build: ./fuseki
    container_name: fuseki
    restart: always
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx1G
    volumes:
      - fuseki_data:/fuseki
    networks:
      - knowledge_net

networks:
  knowledge_net:

volumes:
  mongo_data:
  fuseki_data:
